from __future__ import annotations

import logging
from dataclasses import dataclass
from functools import partial
from itertools import product
from typing import Any

import numpy as np
import pandas as pd

from src.backtest.engine import (
    extract_trades,
    run_candidate_backtest,
)
from src.backtest.metrics import (
    calculate_return_metrics,
    infer_periods_per_year,
)
from src.backtest.result import BacktestResult
from src.factory.candidate import CandidateSpec
from src.factory.parallel import get_worker_market_data, run_parallel_map


logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SampleSplit:
    """
    Chronological in-sample and out-of-sample boundaries.
    """

    in_sample_start: pd.Timestamp
    in_sample_end: pd.Timestamp
    out_of_sample_start: pd.Timestamp

    @classmethod
    def from_config(
        cls,
        sample_config: dict[str, Any],
    ) -> "SampleSplit":
        return cls(
            in_sample_start=pd.Timestamp(
                sample_config["in_sample_start"]
            ).tz_localize("UTC"),
            in_sample_end=pd.Timestamp(
                sample_config["in_sample_end"]
            ).tz_localize("UTC"),
            out_of_sample_start=pd.Timestamp(
                sample_config["out_of_sample_start"]
            ).tz_localize("UTC"),
        )

    def validate(self) -> None:
        if self.in_sample_start > self.in_sample_end:
            raise ValueError(
                "in_sample_start must not be after in_sample_end."
            )

        if self.out_of_sample_start <= self.in_sample_end:
            raise ValueError(
                "out_of_sample_start must be after in_sample_end."
            )


def slice_backtest_window(
    timeseries: pd.DataFrame,
    start: pd.Timestamp,
    end: pd.Timestamp | None = None,
) -> pd.DataFrame:
    """
    Extract a chronological window from a completed backtest.
    """
    if end is None:
        window = timeseries.loc[
            timeseries.index >= start
        ].copy()
    else:
        window = timeseries.loc[
            (timeseries.index >= start)
            & (timeseries.index <= end)
        ].copy()

    if window.empty:
        raise ValueError(
            f"No backtest observations found from {start} to {end}."
        )

    return window


def extract_window_trades(
    window_data: pd.DataFrame,
) -> pd.DataFrame:
    """
    Extract position episodes contained in an evaluation window.

    A position carried into the first window observation is included as a
    partial window trade because its returns and risks occur inside the
    evaluation period.
    """
    return extract_trades(window_data)


def calculate_top_trade_profit_share(
    trades: pd.DataFrame,
    top_n: int = 5,
) -> float:
    """
    Measure concentration of positive net trade profits.

    Returns the share of total positive trade profits generated by the
    largest top_n profitable trades.

    A value close to 1 means profitability depends on very few trades.
    """
    if trades.empty:
        return np.nan

    positive_trade_returns = (
        trades.loc[
            trades["net_trade_return"] > 0,
            "net_trade_return",
        ]
        .sort_values(ascending=False)
    )

    if positive_trade_returns.empty:
        return 1.0

    total_positive_profit = positive_trade_returns.sum()

    if total_positive_profit <= 0:
        return 1.0

    top_profit = positive_trade_returns.head(top_n).sum()

    return float(top_profit / total_positive_profit)


def calculate_window_metrics(
    window_data: pd.DataFrame,
    prefix: str,
) -> tuple[dict[str, float | int], pd.DataFrame]:
    """
    Recompute performance and trading metrics within one sample window.
    """
    required_columns = {
        "gross_return",
        "net_return",
        "executed_position",
        "position_change",
        "transaction_cost",
    }

    missing_columns = required_columns.difference(
        window_data.columns
    )

    if missing_columns:
        raise ValueError(
            f"Window data is missing columns: "
            f"{sorted(missing_columns)}"
        )

    periods_per_year = infer_periods_per_year(
        window_data.index
    )

    metrics: dict[str, float | int] = {}

    metrics.update(
        calculate_return_metrics(
            returns=window_data["gross_return"],
            periods_per_year=periods_per_year,
            prefix=f"{prefix}_gross",
        )
    )

    metrics.update(
        calculate_return_metrics(
            returns=window_data["net_return"],
            periods_per_year=periods_per_year,
            prefix=f"{prefix}_net",
        )
    )

    trades = extract_window_trades(window_data)

    window_start = window_data.index.min()

    if trades.empty:
        trades_for_count = trades
    else:
        trades_for_count = trades.loc[
            trades["entry_timestamp"] >= window_start
        ].copy()

    metrics.update(
        {
            f"{prefix}_observation_count": int(
                len(window_data)
            ),
            f"{prefix}_trade_count": int(
                len(trades_for_count)
            ),
            f"{prefix}_position_change_count": int(
                (window_data["position_change"] != 0).sum()
            ),
            f"{prefix}_total_transaction_cost": float(
                window_data["transaction_cost"].sum()
            ),
            f"{prefix}_long_fraction": float(
                (
                    window_data["executed_position"] == 1
                ).mean()
            ),
            f"{prefix}_short_fraction": float(
                (
                    window_data["executed_position"] == -1
                ).mean()
            ),
            f"{prefix}_flat_fraction": float(
                (
                    window_data["executed_position"] == 0
                ).mean()
            ),
            f"{prefix}_top_5_trade_profit_share": (
                calculate_top_trade_profit_share(
                    trades=trades_for_count,
                    top_n=5,
                )
            ),
        }
    )

    return metrics, trades_for_count


def perturb_integer_parameter(
    value: int,
    perturbation: float,
) -> list[int]:
    """
    Produce rounded lower and upper integer neighbors.
    """
    lower = max(
        1,
        int(round(value * (1.0 - perturbation))),
    )

    upper = max(
        1,
        int(round(value * (1.0 + perturbation))),
    )

    return sorted({lower, upper})


def perturb_float_parameter(
    value: float,
    perturbation: float,
) -> list[float]:
    """
    Produce lower and upper floating-point neighbors.
    """
    lower = round(
        value * (1.0 - perturbation),
        6,
    )

    upper = round(
        value * (1.0 + perturbation),
        6,
    )

    return sorted({lower, upper})


def generate_parameter_neighbors(
    candidate: CandidateSpec,
    perturbation: float = 0.20,
) -> list[CandidateSpec]:
    """
    Generate all unique ±perturbation parameter combinations.

    For two parameters, this normally creates eight surrounding variants:
    - four single-parameter changes;
    - four joint changes.

    The original parameter combination is excluded.
    """
    if not 0 < perturbation < 1:
        raise ValueError(
            "perturbation must lie in the interval (0, 1)."
        )

    parameter_options: dict[
        str,
        list[int | float],
    ] = {}

    for name, value in candidate.parameters.items():
        if isinstance(value, bool):
            raise TypeError(
                f"Boolean parameter '{name}' is unsupported."
            )

        if isinstance(value, int):
            perturbed = perturb_integer_parameter(
                value=value,
                perturbation=perturbation,
            )

        elif isinstance(value, float):
            perturbed = perturb_float_parameter(
                value=value,
                perturbation=perturbation,
            )

        else:
            raise TypeError(
                f"Unsupported parameter type for '{name}': "
                f"{type(value)}"
            )

        parameter_options[name] = sorted(
            set([value, *perturbed])
        )

    parameter_names = sorted(parameter_options)

    neighbors: list[CandidateSpec] = []

    original_parameters = candidate.parameters

    for combination in product(
        *[
            parameter_options[name]
            for name in parameter_names
        ]
    ):
        parameters = dict(
            zip(parameter_names, combination)
        )

        if parameters == original_parameters:
            continue

        if candidate.family == "trend":
            fast_window = int(
                parameters["fast_window"]
            )
            slow_window = int(
                parameters["slow_window"]
            )

            if fast_window >= slow_window:
                continue

            parameters = {
                "fast_window": fast_window,
                "slow_window": slow_window,
            }

        elif candidate.family == "mean_reversion":
            parameters = {
                "lookback": int(
                    parameters["lookback"]
                ),
                "entry_z": float(
                    parameters["entry_z"]
                ),
            }

        elif candidate.family == "momentum":
            parameters = {
                "lookback": int(
                    parameters["lookback"]
                ),
                "threshold": float(
                    parameters["threshold"]
                ),
            }

        elif candidate.family == "volatility":
            parameters = {
                "window": int(
                    parameters["window"]
                ),
                "num_std": float(
                    parameters["num_std"]
                ),
            }

        elif candidate.family == "stat_arb":
            parameters = {
                "lookback": int(
                    parameters["lookback"]
                ),
                "entry_z": float(
                    parameters["entry_z"]
                ),
            }

        elif candidate.family == "carry":
            parameters = {
                "threshold": float(
                    parameters["threshold"]
                ),
            }

        else:
            raise ValueError(
                f"Unsupported family: {candidate.family}"
            )

        neighbors.append(
            CandidateSpec(
                family=candidate.family,
                symbol=candidate.symbol,
                parameters=parameters,
            )
        )

    unique_neighbors = {
        neighbor.candidate_id: neighbor
        for neighbor in neighbors
    }

    return list(unique_neighbors.values())


def evaluate_oos_performance_criteria(
    oos_metrics: dict[str, float | int],
    criteria: dict[str, Any],
) -> tuple[bool, list[str]]:
    """
    Apply the fixed Layer 1 OOS performance thresholds.
    """
    failures: list[str] = []

    net_sharpe = float(
        oos_metrics["oos_net_sharpe"]
    )

    net_return = float(
        oos_metrics["oos_net_total_return"]
    )

    trade_count = int(
        oos_metrics["oos_trade_count"]
    )

    concentration = float(
        oos_metrics[
            "oos_top_5_trade_profit_share"
        ]
    )

    if (
        not np.isfinite(net_sharpe)
        or net_sharpe
        < criteria["minimum_oos_net_sharpe"]
    ):
        failures.append("oos_net_sharpe")

    if (
        not np.isfinite(net_return)
        or net_return
        <= criteria["minimum_oos_net_return"]
    ):
        failures.append("oos_net_return")

    if trade_count < criteria["minimum_oos_trades"]:
        failures.append("oos_trade_count")

    if (
        not np.isfinite(concentration)
        or concentration
        > criteria[
            "maximum_top_5_trade_profit_share"
        ]
    ):
        failures.append("trade_profit_concentration")

    return len(failures) == 0, failures


def evaluate_neighbor_criteria(
    neighbor_results: pd.DataFrame,
    criteria: dict[str, Any],
) -> tuple[bool, list[str], dict[str, float | int]]:
    """
    Apply parameter-sensitivity thresholds.
    """
    failures: list[str] = []

    if neighbor_results.empty:
        summary = {
            "neighbor_count": 0,
            "positive_neighbor_count": 0,
            "median_neighbor_sharpe": np.nan,
            "worst_neighbor_sharpe": np.nan,
        }

        return False, ["no_valid_neighbors"], summary

    sharpe = neighbor_results[
        "oos_net_sharpe"
    ]

    return_values = neighbor_results[
        "oos_net_total_return"
    ]

    positive_mask = (
        (return_values > 0)
        & sharpe.notna()
    )

    positive_neighbor_count = int(
        positive_mask.sum()
    )

    median_neighbor_sharpe = float(
        sharpe.median()
    )

    worst_neighbor_sharpe = float(
        sharpe.min()
    )

    if (
        positive_neighbor_count
        < criteria["minimum_positive_neighbors"]
    ):
        failures.append("positive_neighbor_count")

    if (
        not np.isfinite(median_neighbor_sharpe)
        or median_neighbor_sharpe
        < criteria[
            "minimum_median_neighbor_sharpe"
        ]
    ):
        failures.append("median_neighbor_sharpe")

    if (
        not np.isfinite(worst_neighbor_sharpe)
        or worst_neighbor_sharpe
        < criteria[
            "minimum_worst_neighbor_sharpe"
        ]
    ):
        failures.append("worst_neighbor_sharpe")

    summary = {
        "neighbor_count": int(
            len(neighbor_results)
        ),
        "positive_neighbor_count": (
            positive_neighbor_count
        ),
        "median_neighbor_sharpe": (
            median_neighbor_sharpe
        ),
        "worst_neighbor_sharpe": (
            worst_neighbor_sharpe
        ),
    }

    return len(failures) == 0, failures, summary


def evaluate_neighbor_population(
    candidate: CandidateSpec,
    market_data: pd.DataFrame,
    split: SampleSplit,
    perturbation: float,
    commission_bps_per_side: float,
) -> pd.DataFrame:
    """
    Backtest and evaluate all parameter neighbors in the OOS window.
    """
    neighbors = generate_parameter_neighbors(
        candidate=candidate,
        perturbation=perturbation,
    )

    records: list[dict[str, Any]] = []

    for neighbor in neighbors:
        result = run_candidate_backtest(
            candidate=neighbor,
            market_data=market_data,
            commission_bps_per_side=(
                commission_bps_per_side
            ),
        )

        oos_data = slice_backtest_window(
            timeseries=result.timeseries,
            start=split.out_of_sample_start,
        )

        oos_metrics, _ = calculate_window_metrics(
            window_data=oos_data,
            prefix="oos",
        )

        records.append(
            {
                "parent_candidate_id": (
                    candidate.candidate_id
                ),
                "neighbor_candidate_id": (
                    neighbor.candidate_id
                ),
                "family": neighbor.family,
                "symbol": neighbor.symbol,
                **neighbor.parameters,
                "oos_net_total_return": (
                    oos_metrics[
                        "oos_net_total_return"
                    ]
                ),
                "oos_net_annual_return": (
                    oos_metrics[
                        "oos_net_annual_return"
                    ]
                ),
                "oos_net_sharpe": (
                    oos_metrics[
                        "oos_net_sharpe"
                    ]
                ),
                "oos_net_max_drawdown": (
                    oos_metrics[
                        "oos_net_max_drawdown"
                    ]
                ),
                "oos_trade_count": (
                    oos_metrics["oos_trade_count"]
                ),
            }
        )

    return pd.DataFrame(records)


def evaluate_layer1_candidate(
    result: BacktestResult,
    market_data: pd.DataFrame,
    split: SampleSplit,
    layer1_criteria: dict[str, Any],
    commission_bps_per_side: float = 0.5,
) -> tuple[
    dict[str, Any],
    pd.DataFrame,
]:
    """
    Evaluate one official candidate under Layer 1.
    """
    split.validate()

    is_data = slice_backtest_window(
        timeseries=result.timeseries,
        start=split.in_sample_start,
        end=split.in_sample_end,
    )

    oos_data = slice_backtest_window(
        timeseries=result.timeseries,
        start=split.out_of_sample_start,
    )

    is_metrics, _ = calculate_window_metrics(
        window_data=is_data,
        prefix="is",
    )

    oos_metrics, _ = calculate_window_metrics(
        window_data=oos_data,
        prefix="oos",
    )

    performance_pass, performance_failures = (
        evaluate_oos_performance_criteria(
            oos_metrics=oos_metrics,
            criteria=layer1_criteria,
        )
    )

    neighbor_results = evaluate_neighbor_population(
        candidate=result.candidate,
        market_data=market_data,
        split=split,
        perturbation=float(
            layer1_criteria[
                "parameter_perturbation"
            ]
        ),
        commission_bps_per_side=(
            commission_bps_per_side
        ),
    )

    (
        sensitivity_pass,
        sensitivity_failures,
        sensitivity_summary,
    ) = evaluate_neighbor_criteria(
        neighbor_results=neighbor_results,
        criteria=layer1_criteria,
    )

    layer1_pass = (
        performance_pass
        and sensitivity_pass
    )

    all_failures = [
        *performance_failures,
        *sensitivity_failures,
    ]

    record: dict[str, Any] = {
        **result.candidate.to_dict(),
        "is_start": is_data.index.min(),
        "is_end": is_data.index.max(),
        "oos_start": oos_data.index.min(),
        "oos_end": oos_data.index.max(),
        **is_metrics,
        **oos_metrics,
        **sensitivity_summary,
        "performance_pass": performance_pass,
        "sensitivity_pass": sensitivity_pass,
        "layer1_pass": layer1_pass,
        "failure_reason": (
            ";".join(all_failures)
            if all_failures
            else ""
        ),
    }

    return record, neighbor_results


def _evaluate_layer1_candidate_worker(
    result: BacktestResult,
    split: SampleSplit,
    layer1_criteria: dict[str, Any],
    commission_bps_per_side: float,
) -> tuple[dict[str, Any], pd.DataFrame]:
    """
    Worker-process entry point for parallel Layer 1 evaluation: resolves
    this candidate's market data from the pool-initialized worker-local
    store (src.factory.parallel) instead of receiving the full
    processed_data dict as an argument, so it isn't re-pickled per task.
    """
    market_data = get_worker_market_data()[result.candidate.symbol]

    return evaluate_layer1_candidate(
        result=result,
        market_data=market_data,
        split=split,
        layer1_criteria=layer1_criteria,
        commission_bps_per_side=commission_bps_per_side,
    )


def run_layer1_gate(
    backtest_results: dict[str, BacktestResult],
    processed_data: dict[str, pd.DataFrame],
    sample_config: dict[str, Any],
    layer1_config: dict[str, Any],
    commission_bps_per_side: float = 0.5,
    executor: Any = None,
) -> tuple[
    pd.DataFrame,
    pd.DataFrame,
]:
    """
    Evaluate all official candidates under Layer 1.

    executor is an optional concurrent.futures.ProcessPoolExecutor (see
    src.factory.parallel) whose worker processes were already initialized
    with this run's market data. Pass None (the default) to evaluate
    candidates sequentially in-process, exactly as before.
    """
    split = SampleSplit.from_config(
        sample_config
    )

    split.validate()

    candidate_records: list[dict[str, Any]] = []
    neighbor_frames: list[pd.DataFrame] = []

    if executor is None:
        for candidate_id, result in backtest_results.items():
            logger.debug(f"Layer 1: {candidate_id}")

            symbol = result.candidate.symbol

            record, neighbors = (
                evaluate_layer1_candidate(
                    result=result,
                    market_data=processed_data[symbol],
                    split=split,
                    layer1_criteria=layer1_config,
                    commission_bps_per_side=(
                        commission_bps_per_side
                    ),
                )
            )

            candidate_records.append(record)
            neighbor_frames.append(neighbors)
    else:
        worker = partial(
            _evaluate_layer1_candidate_worker,
            split=split,
            layer1_criteria=layer1_config,
            commission_bps_per_side=commission_bps_per_side,
        )

        for record, neighbors in run_parallel_map(
            executor, worker, backtest_results.values()
        ):
            candidate_records.append(record)
            neighbor_frames.append(neighbors)

    layer1_results = pd.DataFrame(
        candidate_records
    )

    all_neighbor_results = (
        pd.DataFrame()
        if not neighbor_frames
        else pd.concat(
            neighbor_frames,
            ignore_index=True,
        )
    )

    if len(layer1_results) != len(backtest_results):
        raise RuntimeError(
            "Layer 1 did not produce one row per candidate."
        )

    if not layer1_results.empty and not layer1_results[
        "candidate_id"
    ].is_unique:
        raise RuntimeError(
            "Layer 1 produced duplicate candidate IDs."
        )

    return layer1_results, all_neighbor_results